### ISSUE TITLE
Won't show on toolbar of Cura 4.11.0

### ISSUE THREAD

**Issue by Build-0-Matic** [5axes/TabAntiWarping#10]
Tab Anti-Warping won't show on the left toolbar of Cura 4.11.0 (Windows 10 64 bit)
I tried uninstalling and re-installing to no effect.

**Comment by 5axes** [comment]
Strange , Work Fine for me,  
Did you check the **plugins** directory ? do you have the folder  **TabAntiWarping** present ?
Any message in the Log file regarding the TabAntiWarping plugin ?

**Comment by Build-0-Matic** [comment]
I think I found the problem.
`2021-09-23 12:27:55,173 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [426]: Plugin [TabAntiWarping] has been disabled. Skip loading it.`

Now the thing is how do I fix it?

**Comment by Build-0-Matic** [comment]
OK! Fixed it!
For some odd reason it installed it as disabled... can't figure out why.
Enabled it and now it works.

Thanks for pointing me in the right direction.
