### ISSUE TITLE
Need to untick "Ensure models are kept apart"

### ISSUE THREAD

**Issue by richard-scott** [5axes/TabAntiWarping#12]
Hi is there any way the plugin can be excluded from processing by the "Ensure models are kept apart" option in Cura?
With that setting enabled, I get some really strange results and my 2nd tab is pushed off the build area as this option makes sure the models are kept apart.

**Comment by 5axes** [comment]
Yes looks like a Cura Issue. Cannot do anything on the Plugin Level.

**Comment by 5axes** [comment]
Don't use the option "**Ensure models are kept apart**" when you use this plugin.

![image](https://user-images.githubusercontent.com/11015345/148852419-cc5c4207-1fcf-4ab8-bb86-3f964279b27c.png)
