### ISSUE TITLE
Cura 5 marketplace

### ISSUE THREAD

**Issue by nfacha** [5axes/TabAntiWarping#16]
Hello
I see an update for CUra 5 has been released (https://github.com/5axes/TabAntiWarping/releases/tag/V1.3.0) although I cant find it on the marketplace, was the listing there updated?

**Comment by 5axes** [comment]
Sorry,

No update scheduled via the market place until to get a stable Cura 5.0 release.

If you want to test the plugin you have to install it via the Curapackage on this Github.
