### ISSUE TITLE
Creality Slicer 4.8 (cura) wont enable plugin from marketplace, install from github worked.

### ISSUE THREAD

**Issue by hayden-t** [5axes/TabAntiWarping#17]
Would just always be unticked, and when you tick it it would say will install after restart but it would still be unticked. Installing manually from github worked thanks !

**Comment by 5axes** [comment]
Upstream issue , it's something to report to Creality.  This plugin ( and most of the existing plugin) are only designed for Ultimaker  Cura. There is no assurance that they will work with other versions of Cura.

**Comment by hayden-t** [comment]
totally understand that and expected it, just leaving record for someone else, i guess i could have just closed my own issue to show this
