### ISSUE TITLE
Tabs are not created with a dense structure

### ISSUE THREAD

**Issue by plexi32** [5axes/TabAntiWarping#23]
ok with printer profil Creality CR-10s Pro
not ok with Profil Prusa i3 Mk3/Mk3s (see [picture)]([url]([url](![tab](https://user-images.githubusercontent.com/58932224/214532524-6dbd3c9a-a2d0-408b-8996-fd9c8b1eaab7.png))))
Cura 5.2.1
![tab](https://user-images.githubusercontent.com/58932224/214532984-f85552e5-4682-4738-aaae-5770e7ecb987.jpg)

**Comment by 5axes** [comment]
First of all  : https://github.com/5axes/TabAntiWarping/wiki/Cura-Settings-for-the-Anti-Warping-Tab-Plugin
Then certainly duplicate  : https://github.com/5axes/TabAntiWarping/issues/13
