### ISSUE TITLE
Help needed. Models with chamfer

### ISSUE THREAD

**Issue by DimaSes99** [5axes/TabAntiWarping#25]
Hello! 
For some reason I get this when I try to add tabs to a modem with chamfers.
![зображення](https://github.com/5axes/TabAntiWarping/assets/61504437/964962d7-dd81-498e-ae6f-78d415e32708)
I want a solid connection with a model.  What settings do I need to change to achive this?
When I use the same settings and add a tab to a calibration cube (which has no chamfers), everything works as intended.

**Comment by 5axes** [comment]
Strange .. Graphic issue or real nozzle path ? 
Anyway it's a Cura Issue, cannot do anything  on the Plugin Side.

**Comment by DimaSes99** [comment]
> Strange .. Graphic issue or real nozzle path ? Anyway it's a Cura Issue, cannot do anything on the Plugin Side.

It's real nozzle path. And because of it bed adhesion is not very good for  tabs.
Anyway, thanks for the fast reply!

**Comment by DimaSes99** [comment]
I figured out. It was because of support interface. It should be disabled.
![зображення](https://github.com/5axes/TabAntiWarping/assets/61504437/128d30c0-fd8f-47b5-a1f5-5089a7fddf5e)

**Comment by 5axes** [comment]
I thought your issue was the small blue lines under the model 😃
